cmake_minimum_required(VERSION 4.4.2)
project(OmniTank LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 26)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
add_library(omni_tank SHARED Tank.cpp)
target_include_directories(omni_tank PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})
target_compile_features(omni_tank PRIVATE cxx_std_26)
target_compile_options(omni_tank PRIVATE -Wall -Wextra -Wpedantic)
find_library(log-lib log)
target_link_libraries(omni_tank PRIVATE ${log-lib})
